apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: default
spec:
  tracing:
    samplingRate: "1"
  mtls:
    enabled: true
    workloadCertTTL: 24h
    allowedClockSkew: 15m